const express = require("express");
const cors = require("cors");
const mysql = require('mysql2');

const app = express();
app.use(cors());
app.use(express.json()); // To parse JSON bodies in requests

const port = 8081;

// MySQL Database Connection
const db = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: "",
    database: "franchise_athletica",
    port:3307
});

// Connect to MySQL
db.connect((err) => {
    if (err) {
        console.error('Database connection failed: ' + err.stack);
        return;
    }
    console.log('Connected to MySQL as ID ' + db.threadId);
});


app.post('/api/contact', (req, res) => {
    const sql = "INSERT INTO contact (`name`, `email`,`mobile`,`message`,`created_at` ,`updated_at` ) VALUES (?, ?, ?, ?,NOW(),NOW())";
    const values = [
       
        req.body.name,
        req.body.email,
        req.body.mobile,
        req.body.message

    ];

    db.query(sql, values, (err, data) => {
        if (err) {
            console.error('Error inserting data: ', err);
            return res.status(500).json({ error: "Failed to insert data" });
        }
        return res.json({ message: "Data inserted successfully", data });
    });
});

// app.post('/api/register', (req, res) => {
//     const sql = `
//   INSERT INTO school_sports (
//     school_name,
//     campus,
//     principal_email,
//     principal_name ,
//     principal_mobile,
//     sports_incharge,
//     incharge_mobile,
//     male_teacher,
//     male_teacher_mobile,
//     female_teacher,
//     female_teacher_mobile,
//     u12_boy_name_80mtr,
//     u12_boy_classes_80mtr,
//     u12_boy_dob_80mtr,
//     u12_girl_name_80mtr,
//     u12_girl_classes_80mtr,
//     u12_girl_dob_80mtr,
//     u14_boy_name_100mtr,
//     u14_boy_classes_100mtr,
//     u14_girl_classes_100mtr,
//     u14_boy_dob_100mtr,
//     u14_girl_name_100mtr,
//     u14_girl_dob_100mtr,
//     u17_boy_name_100mtr,
//     u17_boy_classes_100mtr,
//     u17_boy_dob_100mtr,
//     u17_girl_name_100mtr ,
//     u17_girl_classes_100mtr,
//     u17_girl_dob_100mtr,
//     u14_boy_name_200mtr,
//     u14_boy_classes_200mtr,
//     u14_girl_classes_200mtr ,
//     u14_boy_dob_200mtr,
//     u14_girl_name_200mtr,
//     u14_girl_dob_200mtr ,
//     u17_boy_name_200mtr ,
//     u17_boy_classes_200mtr,
//     u17_boy_dob_200mtr,
//     u17_girl_name_200mtr,
//     u17_girl_classes_200mtr,
//     u17_girl_dob_200mtr,
//     u14_boy_name_400mtr,
//     u14_boy_classes_400mtr,
//     u14_girl_classes_400mtr,
//     u14_boy_dob_400mtr,
//     u14_girl_name_400mtr,
//     u14_girl_dob_400mtr,
//     u17_boy_name_400mtr,
//     u17_boy_classes_400mtr,
//     u17_boy_dob_400mtr,
//     u17_girl_name_400mtr,
//     u17_girl_classes_400mtr,
//     u17_girl_dob_400mtr,
//     u17_boy_name_hurdlerace,
//     u17_boy_classes_hurdlerace,
//     u17_boy_dob_hurdlerace,
//     u17_girl_name_hurdlerace,
//     u17_girl_classes_hurdlerace,
//     u17_girl_dob_hurdlerace,
//     u14_boy_name_longjump,
//     u14_boy_classes_longjump,
//     u14_girl_classes_longjump,
//     u14_boy_dob_longjump,
//     u14_girl_name_longjump,
//     u14_girl_dob_longjump ,
//     u17_boy_name_longjump,
//     u17_boy_classes_longjump ,
//     u17_boy_dob_longjump,
//     u17_girl_name_longjump ,
//     u17_girl_classes_longjump ,
//     u17_girl_dob_longjump DATE,
//     u14_boy_name_relay_race_1,
//     u14_boy_classes_relay_race_1,
//     u14_girl_classes_relay_race_1,
//     u14_boy_dob_relay_race_1,
//     u14_girl_name_relay_race_1,
//     u14_girl_dob_relay_race_1,
//     u17_boy_name_relay_race_1 ,
//     u17_boy_classes_relay_race_1 ,
//     u17_boy_dob_relay_race_1 ,
//     u17_girl_name_relay_race_1 ,
//     u17_girl_classes_relay_race_1 ,
//     u17_girl_dob_relay_race_1,
//     u14_boy_name_relay_race_2,
//     u14_boy_classes_relay_race_2 ,
//     u14_girl_classes_relay_race_2 ,
//     u14_boy_dob_relay_race_2 ,
//     u14_girl_name_relay_race_2 ,
//     u14_girl_dob_relay_race_2 ,
//     u17_boy_name_relay_race_2 ,
//     u17_boy_classes_relay_race_2 ,
//     u17_boy_dob_relay_race_2 ,
//     u17_girl_name_relay_race_2 ,
//     u17_girl_classes_relay_race_2 ,
//     u17_girl_dob_relay_race_2 ,
//     u14_boy_name_relay_race_3 ,
//     u14_boy_classes_relay_race_3 ,
//     u14_girl_classes_relay_race_3 ,
//     u14_boy_dob_relay_race_3 ,
//     u14_girl_name_relay_race_3 ,
//     u14_girl_dob_relay_race_3 ,
//     u17_boy_name_relay_race_3 ,
//     u17_boy_classes_relay_race_3 ,
//     u17_boy_dob_relay_race_3 ,
//     u17_girl_name_relay_race_3 ,
//     u17_girl_classes_relay_race_3 ,
//     u17_girl_dob_relay_race_3 ,
//     u14_boy_name_relay_race_4 ,
//     u14_boy_classes_relay_race_4 ,
//     u14_girl_classes_relay_race_4 ,
//     u14_boy_dob_relay_race_4 ,
//     u14_girl_name_relay_race_4 ,
//     u14_girl_dob_relay_race_4 ,
//     u17_boy_name_relay_race_4 ,
//     u17_boy_classes_relay_race_4 ,
//     u17_boy_dob_relay_race_4 ,
//     u17_girl_name_relay_race_4 ,
//     u17_girl_classes_relay_race_4 ,
//     u17_girl_dob_relay_race_4 ,
//     u14_boy_name_short_put ,
//     u14_boy_classes_short_put ,
//     u14_girl_classes_short_put ,
//     u14_boy_dob_short_put ,
//     u14_girl_name_short_put ,
//     u14_girl_dob_short_put ,
//     u17_boy_name_short_put ,
//     u17_boy_classes_short_put ,
//     u17_boy_dob_short_put ,
//     u17_girl_name_short_put ,
//     u17_girl_classes_short_put ,
//     u17_girl_dob_short_put ,
//     u14_boy_name_badminton ,
//     u14_boy_classes_badminton ,
//     u14_girl_classes_badminton ,
//     u14_boy_dob_badminton,
//     u14_girl_name_badminton ,
//     u14_girl_dob_badminton ,
//     u17_boy_name_badminton ,
//     u17_boy_classes_badminton ,
//     u17_boy_dob_badminton ,
//     u17_girl_name_badminton ,
//     u17_girl_classes_badminton ,
//     u17_girl_dob_badminton ,
//     u14_boy_name_chess ,
//     u14_boy_classes_chess ,
//     u14_girl_classes_chess ,
//     u14_boy_dob_chess ,
//     u14_girl_name_chess,
//     u14_girl_dob_chess ,
//     u17_boy_name_chess ,
//     u17_boy_classes_chess ,
//     u17_boy_dob_chess ,
//     u17_girl_name_chess ,
//     u17_girl_classes_chess ,
//     u17_girl_dob_chess ,
//     u14_boy_name_table_tennis ,
//     u14_boy_classes_table_tennis ,
//     u14_girl_classes_table_tennis ,
//     u14_boy_dob_table_tennis ,
//     u14_girl_name_table_tennis ,
//     u14_girl_dob_table_tennis ,
//     u17_boy_name_table_tennis,
//     u17_boy_classes_table_tennis ,
//     u17_boy_dob_table_tennis ,
//     u17_girl_name_table_tennis ,
//     u17_girl_classes_table_tennis ,
//     u17_girl_dob_table_tennis,
//     created_at ,
//     updated_at 
//   ) 
//   VALUES (
//     ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW()
//   );
// `;


// const values = [
//     req.body.school_name,
//     req.body.campus,
//     req.body.principal_email,
//     req.body.principal_name,
//     req.body.principal_mobile,
//     req.body.sports_incharge,
//     req.body.incharge_mobile,
//     req.body.male_teacher,
//     req.body.male_teacher_mobile,
//     req.body.female_teacher,
//     req.body.female_teacher_mobile,
//     req.body.u12_boy_name_80mtr,
//     req.body.u12_boy_classes_80mtr,
//     req.body.u12_boy_dob_80mtr,
//     req.body.u12_girl_name_80mtr,
//     req.body.u12_girl_classes_80mtr,
//     req.body.u12_girl_dob_80mtr,
//     req.body.u14_boy_name_100mtr,
//     req.body.u14_boy_classes_100mtr,
//     req.body.u14_girl_classes_100mtr,
//     req.body.u14_boy_dob_100mtr,
//     req.body.u14_girl_name_100mtr,
//     req.body.u14_girl_dob_100mtr,
//     req.body.u17_boy_name_100mtr,
//     req.body.u17_boy_classes_100mtr,
//     req.body.u17_boy_dob_100mtr,
//     req.body.u17_girl_name_100mtr,
//     req.body.u17_girl_classes_100mtr,
//     req.body.u17_girl_dob_100mtr,
//     req.body.u14_boy_name_200mtr,
//     req.body.u14_boy_classes_200mtr,
//     req.body.u14_girl_classes_200mtr,
//     req.body.u14_boy_dob_200mtr,
//     req.body.u14_girl_name_200mtr,
//     req.body.u14_girl_dob_200mtr,
//     req.body.u17_boy_name_200mtr,
//     req.body.u17_boy_classes_200mtr,
//     req.body.u17_boy_dob_200mtr,
//     req.body.u17_girl_name_200mtr,
//     req.body.u17_girl_classes_200mtr,
//     req.body.u17_girl_dob_200mtr,
//     req.body.u14_boy_name_400mtr,
//     req.body.u14_boy_classes_400mtr,
//     req.body.u14_girl_classes_400mtr,
//     req.body.u14_boy_dob_400mtr,
//     req.body.u14_girl_name_400mtr,
//     req.body.u14_girl_dob_400mtr,
//     req.body.u17_boy_name_400mtr,
//     req.body.u17_boy_classes_400mtr,
//     req.body.u17_boy_dob_400mtr,
//     req.body.u17_girl_name_400mtr,
//     req.body.u17_girl_classes_400mtr,
//     req.body.u17_girl_dob_400mtr,
//     req.body.u17_boy_name_hurdlerace,
//     req.body.u17_boy_classes_hurdlerace,
//     req.body.u17_boy_dob_hurdlerace,
//     req.body.u17_girl_name_hurdlerace,
//     req.body.u17_girl_classes_hurdlerace,
//     req.body.u17_girl_dob_hurdlerace,
//     req.body.u14_boy_name_longjump,
//     req.body.u14_boy_classes_longjump,
//     req.body.u14_girl_classes_longjump,
//     req.body.u14_boy_dob_longjump,
//     req.body.u14_girl_name_longjump,
//     req.body.u14_girl_dob_longjump,
//     req.body.u17_boy_name_longjump,
//     req.body.u17_boy_classes_longjump,
//     req.body.u17_boy_dob_longjump,
//     req.body.u17_girl_name_longjump,
//     req.body.u17_girl_classes_longjump,
//     req.body.u17_girl_dob_longjump,
//     req.body.u14_boy_name_relay_race_1,
//     req.body.u14_boy_classes_relay_race_1,
//     req.body.u14_girl_classes_relay_race_1,
//     req.body.u14_boy_dob_relay_race_1,
//     req.body.u14_girl_name_relay_race_1,
//     req.body.u14_girl_dob_relay_race_1,
//     req.body.u17_boy_name_relay_race_1,
//     req.body.u17_boy_classes_relay_race_1,
//     req.body.u17_boy_dob_relay_race_1,
//     req.body.u17_girl_name_relay_race_1,
//     req.body.u17_girl_classes_relay_race_1,
//     req.body.u17_girl_dob_relay_race_1,
//     req.body.u14_boy_name_relay_race_2,
//     req.body.u14_boy_classes_relay_race_2,
//     req.body.u14_girl_classes_relay_race_2,
//     req.body.u14_boy_dob_relay_race_2,
//     req.body.u14_girl_name_relay_race_2,
//     req.body.u14_girl_dob_relay_race_2,
//     req.body.u17_boy_name_relay_race_2,
//     req.body.u17_boy_classes_relay_race_2,
//     req.body.u17_boy_dob_relay_race_2,
//     req.body.u17_girl_name_relay_race_2,
//     req.body.u17_girl_classes_relay_race_2,
//     req.body.u17_girl_dob_relay_race_2,
//     req.body.u14_boy_name_relay_race_3,
//     req.body.u14_boy_classes_relay_race_3,
//     req.body.u14_girl_classes_relay_race_3,
//     req.body.u14_boy_dob_relay_race_3,
//     req.body.u14_girl_name_relay_race_3,
//     req.body.u14_girl_dob_relay_race_3,
//     req.body.u17_boy_name_relay_race_3,
//     req.body.u17_boy_classes_relay_race_3,
//     req.body.u17_boy_dob_relay_race_3,
//     req.body.u17_girl_name_relay_race_3,
//     req.body.u17_girl_classes_relay_race_3,
//     req.body.u17_girl_dob_relay_race_3,
//     req.body.u14_boy_name_relay_race_4,
//     req.body.u14_boy_classes_relay_race_4,
//     req.body.u14_girl_classes_relay_race_4,
//     req.body.u14_boy_dob_relay_race_4,
//     req.body.u14_girl_name_relay_race_4,
//     req.body.u14_girl_dob_relay_race_4,
//     req.body.u17_boy_name_relay_race_4,
//     req.body.u17_boy_classes_relay_race_4,
//     req.body.u17_boy_dob_relay_race_4,
//     req.body.u17_girl_name_relay_race_4,
//     req.body.u17_girl_classes_relay_race_4,
//     req.body.u17_girl_dob_relay_race_4,
//     req.body.u14_boy_name_short_put,
//     req.body.u14_boy_classes_short_put,
//     req.body.u14_girl_classes_short_put,
//     req.body.u14_boy_dob_short_put,
//     req.body.u14_girl_name_short_put,
//     req.body.u14_girl_dob_short_put,
//     req.body.u17_boy_name_short_put,
//     req.body.u17_boy_classes_short_put,
//     req.body.u17_boy_dob_short_put,
//     req.body.u17_girl_name_short_put,
//     req.body.u17_girl_classes_short_put,
//     req.body.u17_girl_dob_short_put,
//     req.body.u14_boy_name_badminton,
//     req.body.u14_boy_classes_badminton,
//     req.body.u14_girl_classes_badminton,
//     req.body.u14_boy_dob_badminton,
//     req.body.u14_girl_name_badminton,
//     req.body.u14_girl_dob_badminton,
//     req.body.u17_boy_name_badminton,
//     req.body.u17_boy_classes_badminton,
//     req.body.u17_boy_dob_badminton,
//     req.body.u17_girl_name_badminton,
//     req.body.u17_girl_classes_badminton,
//     req.body.u17_girl_dob_badminton,
//     req.body.u14_boy_name_chess,
//     req.body.u14_boy_classes_chess,
//     req.body.u14_girl_classes_chess,
//     req.body.u14_boy_dob_chess,
//     req.body.u14_girl_name_chess,
//     req.body.u14_girl_dob_chess,
//     req.body.u17_boy_name_chess,
//     req.body.u17_boy_classes_chess,
//     req.body.u17_boy_dob_chess,
//     req.body.u17_girl_name_chess,
//     req.body.u17_girl_classes_chess,
//     req.body.u17_girl_dob_chess,
//     req.body.u17_boy_name_table_tennis,
//     req.body.u17_boy_classes_table_tennis,
//     req.body.u17_boy_dob_table_tennis,
//     req.body.u17_girl_name_table_tennis,
//     req.body.u17_girl_classes_table_tennis,
//     req.body.u17_girl_dob_table_tennis,
//     req.body.u17_boy_name_yoga,
//     req.body.u17_boy_classes_yoga,
//     req.body.u17_boy_dob_yoga,
//     req.body.u17_girl_name_yoga,
//     req.body.u17_girl_classes_yoga,
//     req.body.u17_girl_dob_yoga
// ];

// // You would then pass this 'values' array to the MySQL query for the INSERT statement.


//     db.query(sql, values, (err, data) => {
//         if (err) {
//             console.error('Error inserting data: ', err);
//             return res.status(500).json({ error: "Failed to insert data" });
//         }
//         return res.json({ message: "Data inserted successfully", data });
//     });
// });


app.listen(port, () => {
    console.log("Server running on port 8081");
});